APP_NAME: "BookMySport"
APP_PORT: "33001"

# MongoDB URI
#DB_URI: "mongodb://user:password@localhost:27017/dbname?authMechanism=SCRAM-SHA-1"
#DB_NAME: "dbname"

# Postgres
DB_URI: "postgresql://postgres:Aman@123@localhost:5432/postgres?sslmode=disable"
